### ISSUE TITLE
[FEATURE] mod suggestion: amunra

### ISSUE THREAD

**Issue by cloverdove** [maggi373/TerralizationModcore#40]
hi it's me
https://www.curseforge.com/minecraft/mc-mods/amun-ra
it would be pretty rad if you added this mod
it should fit in just fine, only problem i can think of with compatibilty would be IDs but that's easily fixable

**Comment by maggi373** [comment]
well we have a bit few ids but i think it will go fine

**Comment by maggi373** [comment]
the mod is scheduled for 2.6.2

**Comment by maggi373** [comment]
eey, it actually got added to 2.6.2
